[package]
name = "hh-launchpad3"
version = "0.1.0"
edition = "2021"

[dependencies]
shuttle-axum = "0.21.0"
shuttle-runtime = "0.21.0"
tokio = "1.29.1"
serde_json = "1.0.100"
serde = "1.0.171"
axum = { version = "0.6.18", features = ["json"] }
