[package]
name = "hh-launchpad3"
version = "0.1.0"
edition = "2021"

[dependencies]
shuttle-axum = "0.20.0"
shuttle-runtime = "0.20.0"
tokio = "1.28.2"
serde_json = "1.0.99"
serde = "1.0.166"
axum = { version = "0.6.18", features = ["json"] }
