[package]
name = "hh-launchpad5"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.18"
bytes = "1.4.0"
hyper = "0.14.27"
image = "0.24.7"
shuttle-axum = "0.22.0"
shuttle-runtime = "0.22.0"
tokio = "1.31.0"
